export const RANKS = [
  {
    rank: "F-",
    title: "Beginner",
    color: "#6B7280",
    minPoints: 0,
    maxPoints: 49,
  },
  {
    rank: "F",
    title: "Newcomer",
    color: "#78716C",
    minPoints: 50,
    maxPoints: 99,
  },
  {
    rank: "F+",
    title: "Apprentice",
    color: "#A16207",
    minPoints: 100,
    maxPoints: 124,
  },
  {
    rank: "E-",
    title: "Learner",
    color: "#B45309",
    minPoints: 125,
    maxPoints: 174,
  },
  {
    rank: "E",
    title: "Explorer",
    color: "#CA8A04",
    minPoints: 175,
    maxPoints: 199,
  },
  {
    rank: "E+",
    title: "Contributor",
    color: "#65A30D",
    minPoints: 200,
    maxPoints: 299,
  },
  {
    rank: "D-",
    title: "Practitioner",
    color: "#4D7C0F",
    minPoints: 300,
    maxPoints: 319,
  },
  {
    rank: "D",
    title: "Skilled",
    color: "#16A34A",
    minPoints: 320,
    maxPoints: 354,
  },
  {
    rank: "D+",
    title: "Reliable",
    color: "#15803D",
    minPoints: 355,
    maxPoints: 399,
  },
  {
    rank: "C-",
    title: "Professional",
    color: "#0891B2",
    minPoints: 400,
    maxPoints: 439,
  },
  {
    rank: "C",
    title: "Advanced",
    color: "#0284C7",
    minPoints: 440,
    maxPoints: 499,
  },
  {
    rank: "C+",
    title: "Expert",
    color: "#2563EB",
    minPoints: 500,
    maxPoints: 749,
  },
  {
    rank: "B-",
    title: "Veteran",
    color: "#4F46E5",
    minPoints: 750,
    maxPoints: 999,
  },
  {
    rank: "B",
    title: "Elite",
    color: "#7C3AED",
    minPoints: 1000,
    maxPoints: 1249,
  },
  {
    rank: "B+",
    title: "Master",
    color: "#9333EA",
    minPoints: 1250,
    maxPoints: 1599,
  },
  {
    rank: "A-",
    title: "Champion",
    color: "#C026D3",
    minPoints: 1600,
    maxPoints: 1999,
  },
  {
    rank: "A",
    title: "Grandmaster",
    color: "#DB2777",
    minPoints: 2000,
    maxPoints: 3149,
  },
  {
    rank: "A+",
    title: "Legend",
    color: "#DC2626",
    minPoints: 3150,
    maxPoints: 3999,
  },
  {
    rank: "S-",
    title: "Mythic",
    color: "#EA580C",
    minPoints: 4000,
    maxPoints: 5499,
  },
  {
    rank: "S",
    title: "Immortal",
    color: "#F97316",
    minPoints: 5500,
    maxPoints: 9999,
  },
  {
    rank: "S+",
    title: "Ascended",
    color: "#F59E0B",
    minPoints: 10000,
    maxPoints: 29999,
  },
  {
    rank: "S++",
    title: "Transcendent",
    color: "#FACC15",
    minPoints: 30000,
    maxPoints: null,
  },
] as const;
