name: Sync Issue Labels to PR

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  cancel-in-progress: true
  group: sync-issue-labels-${{ github.ref }}

jobs:
  copy-labels:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Copy issue labels
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request
            const body = pr.body || "";
            const assignees = pr.assignees

            core.info(`PR body: ${body}`);

            const match = body.toLowerCase().match(/(?:close|closes|fix|fixes|resolve|resolves)\s+#(\d+)/i);

            if (!match) {
              core.info("No linked issue found");
              return;
            }

            const issue_number = Number(match[1])

            const { data: issue } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
            });

            const labels = issue.labels.filter(label => label.name !== "pending").map(label => label.name);

            if (labels.length === 0) {
              core.info("Issue has no labels");
              return;
            }

            try {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels,
              });

              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
                labels: ["pending"]
              })

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
                body: `This issue is taken by${assignees.map((assigne, i) => `${i === 0 ? " " : ", "}@${assigne.login}`)}.`  
              })
            } catch (err) {
              console.log(`Failed for #${issue_number}`, err)
            }

            core.info(`Copied labels: ${labels.join(", ")}`);
